/*

 DOUKUTSUMAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 32 x 32
   Tile set      : C:\Users\yosetani-n\Documents\gbdk\Project\gb-test\GBTD\êŒÇÃì¥åA88.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __doukutsuMap_h_INCLUDE
#define __doukutsuMap_h_INCLUDE

#define doukutsuWidth 32
#define doukutsuHeight 32
#define doukutsuBank 0

extern const unsigned char doukutsu[];

#endif

/* End of DOUKUTSUMAP.H */
