/*

 EYE.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 16 x 16
  Tiles                : 0 to 12

  Palette colors       : Included.
  SGB Palette          : None.
  CGB Palette          : 4 Bits per entry.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

#ifndef __Eye_h_INCLUDE
#define __Eye_h_INCLUDE

/* Bank of tiles. */
#define EyeTileBank 0

/* Gameboy Color palette 1 */
#define EyeTileCGBPal1c0 32767
#define EyeTileCGBPal1c1 30590
#define EyeTileCGBPal1c2 21532
#define EyeTileCGBPal1c3 0

/* Gameboy Color palette 2 */
#define EyeTileCGBPal2c0 32767
#define EyeTileCGBPal2c1 924
#define EyeTileCGBPal2c2 1023
#define EyeTileCGBPal2c3 0

/* CGBpalette entries. */
extern const unsigned char EyeTileCGB[];
/* Start of tile array. */
extern const unsigned char EyeShadowTile[];
extern const unsigned char EyeDownFloatTile[];
extern const unsigned char EyeDownTile[];
extern const unsigned char EyeUpFloatTile[];
extern const unsigned char EyeUpTile[];
extern const unsigned char EyeLeftFloatTile[];
extern const unsigned char EyeLeftTile[];
extern const unsigned char EyeRightFloatTile[];
extern const unsigned char EyeRightTile[];
extern const unsigned char EyeBeamShot1Tile[];
extern const unsigned char EyeBeamShot2Tile[];
extern const unsigned char EyeBeamTateTile[];
extern const unsigned char EyeBeamYokoTile[];


#endif

/* End of EYE.H */
