/*

 HERO.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 16 x 16
  Tiles                : 0 to 18

  Palette colors       : Included.
  SGB Palette          : None.
  CGB Palette          : 4 Bits per entry.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

#ifndef __Hero_h_INCLUDE
#define __Hero_h_INCLUDE

/* Bank of tiles. */
#define HeroBank 0


/* Gameboy Color palette 0 */
#define HeroCGBPal0c0 32767
#define HeroCGBPal0c1 32767
#define HeroCGBPal0c2 3487
#define HeroCGBPal0c3 0

/* Gameboy Color palette 0 */
#define SwordTileCGBPal0c0 32767
#define SwordTileCGBPal0c1 32767
#define SwordTileCGBPal0c2 25368
#define SwordTileCGBPal0c3 0


/* CGBpalette entries. */
extern const unsigned char HeroCGB[];
/* Start of tile array. */
extern const unsigned char HeroDownTile[];
extern const unsigned char HeroDownWalkTile[];
extern const unsigned char HeroLeftTile[];
extern const unsigned char HeroLeftWalkTile[];
extern const unsigned char HeroRightTile[];
extern const unsigned char HeroRightWalkTile[];
extern const unsigned char HeroLeftAttack1Tile[];
extern const unsigned char HeroLeftAttack2Tile[];
extern const unsigned char HeroRightAttack1Tile[];
extern const unsigned char HeroRightAttack2Tile[];
extern const unsigned char HeroDownAttack1Tile[];
extern const unsigned char HeroDownAttack2Tile[];
extern const unsigned char HeroUpAttack1Tile[];
extern const unsigned char HeroUpAttack2Tile[];
extern const unsigned char HeroUpTile[];
extern const unsigned char HeroUpWalkTile[];
extern const unsigned char HeroBlinkTile[]; 
extern const unsigned char SwordRightUpTile[];
extern const unsigned char SwordLeftUpTile[];
extern const unsigned char SwordRightTile[];
extern const unsigned char SwordLeftTile[];
extern const unsigned char SwordUpTile[];
extern const unsigned char SwordDownTile[];
extern const unsigned char SwordRightDownTile[];
extern const unsigned char SwordLeftDownTile[];

#endif

/* End of HERO.H */
