/*

 EYE.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 16 x 16
  Tiles                : 0 to 12

  Palette colors       : Included.
  SGB Palette          : None.
  CGB Palette          : 4 Bits per entry.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

#ifndef __Eye_h_INCLUDE
#define __Eye_h_INCLUDE

/* Bank of tiles. */
#define EyeTileBank 0

/* Super Gameboy palette 0 */
#define EyeTileSGBPal0c0 6076
#define EyeTileSGBPal0c1 8935
#define EyeTileSGBPal0c2 6596
#define EyeTileSGBPal0c3 5344

/* Super Gameboy palette 1 */
#define EyeTileSGBPal1c0 6076
#define EyeTileSGBPal1c1 8935
#define EyeTileSGBPal1c2 6596
#define EyeTileSGBPal1c3 5344

/* Super Gameboy palette 2 */
#define EyeTileSGBPal2c0 6076
#define EyeTileSGBPal2c1 8935
#define EyeTileSGBPal2c2 6596
#define EyeTileSGBPal2c3 5344

/* Super Gameboy palette 3 */
#define EyeTileSGBPal3c0 6076
#define EyeTileSGBPal3c1 8935
#define EyeTileSGBPal3c2 6596
#define EyeTileSGBPal3c3 5344

/* Gameboy Color palette 0 */
#define EyeTileCGBPal0c0 32767
#define EyeTileCGBPal0c1 21456
#define EyeTileCGBPal0c2 992
#define EyeTileCGBPal0c3 0

/* Gameboy Color palette 1 */
#define EyeTileCGBPal1c0 32767
#define EyeTileCGBPal1c1 30590
#define EyeTileCGBPal1c2 21532
#define EyeTileCGBPal1c3 0

/* Gameboy Color palette 2 */
#define EyeTileCGBPal2c0 32767
#define EyeTileCGBPal2c1 924
#define EyeTileCGBPal2c2 1023
#define EyeTileCGBPal2c3 0

/* Gameboy Color palette 3 */
#define EyeTileCGBPal3c0 6076
#define EyeTileCGBPal3c1 8935
#define EyeTileCGBPal3c2 6596
#define EyeTileCGBPal3c3 5344

/* Gameboy Color palette 4 */
#define EyeTileCGBPal4c0 6076
#define EyeTileCGBPal4c1 8935
#define EyeTileCGBPal4c2 6596
#define EyeTileCGBPal4c3 5344

/* Gameboy Color palette 5 */
#define EyeTileCGBPal5c0 6076
#define EyeTileCGBPal5c1 8935
#define EyeTileCGBPal5c2 6596
#define EyeTileCGBPal5c3 5344

/* Gameboy Color palette 6 */
#define EyeTileCGBPal6c0 6076
#define EyeTileCGBPal6c1 8935
#define EyeTileCGBPal6c2 6596
#define EyeTileCGBPal6c3 5344

/* Gameboy Color palette 7 */
#define EyeTileCGBPal7c0 6076
#define EyeTileCGBPal7c1 8935
#define EyeTileCGBPal7c2 6596
#define EyeTileCGBPal7c3 5344
/* CGBpalette entries. */
extern const unsigned char EyeTileCGB[];
/* Start of tile array. */
extern const unsigned char EyeTile[];

#endif

/* End of EYE.H */
