/*

 HERO.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 16 x 16
  Tiles                : 0 to 15

  Palette colors       : Included.
  SGB Palette          : None.
  CGB Palette          : 4 Bits per entry.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

#ifndef __Hero_h_INCLUDE
#define __Hero_h_INCLUDE

/* Bank of tiles. */
#define HeroBank 0

/* Super Gameboy palette 0 */
#define HeroSGBPal0c0 6076
#define HeroSGBPal0c1 8935
#define HeroSGBPal0c2 6596
#define HeroSGBPal0c3 5344

/* Super Gameboy palette 1 */
#define HeroSGBPal1c0 6076
#define HeroSGBPal1c1 8935
#define HeroSGBPal1c2 6596
#define HeroSGBPal1c3 5344

/* Super Gameboy palette 2 */
#define HeroSGBPal2c0 6076
#define HeroSGBPal2c1 8935
#define HeroSGBPal2c2 6596
#define HeroSGBPal2c3 5344

/* Super Gameboy palette 3 */
#define HeroSGBPal3c0 6076
#define HeroSGBPal3c1 8935
#define HeroSGBPal3c2 6596
#define HeroSGBPal3c3 5344

/* Gameboy Color palette 0 */
#define HeroCGBPal0c0 32767
#define HeroCGBPal0c1 32767
#define HeroCGBPal0c2 3487
#define HeroCGBPal0c3 0

/* Gameboy Color palette 1 */
#define HeroCGBPal1c0 6076
#define HeroCGBPal1c1 8935
#define HeroCGBPal1c2 6596
#define HeroCGBPal1c3 5344

/* Gameboy Color palette 2 */
#define HeroCGBPal2c0 6076
#define HeroCGBPal2c1 8935
#define HeroCGBPal2c2 6596
#define HeroCGBPal2c3 5344

/* Gameboy Color palette 3 */
#define HeroCGBPal3c0 6076
#define HeroCGBPal3c1 8935
#define HeroCGBPal3c2 6596
#define HeroCGBPal3c3 5344

/* Gameboy Color palette 4 */
#define HeroCGBPal4c0 6076
#define HeroCGBPal4c1 8935
#define HeroCGBPal4c2 6596
#define HeroCGBPal4c3 5344

/* Gameboy Color palette 5 */
#define HeroCGBPal5c0 6076
#define HeroCGBPal5c1 8935
#define HeroCGBPal5c2 6596
#define HeroCGBPal5c3 5344

/* Gameboy Color palette 6 */
#define HeroCGBPal6c0 6076
#define HeroCGBPal6c1 8935
#define HeroCGBPal6c2 6596
#define HeroCGBPal6c3 5344

/* Gameboy Color palette 7 */
#define HeroCGBPal7c0 6076
#define HeroCGBPal7c1 8935
#define HeroCGBPal7c2 6596
#define HeroCGBPal7c3 5344
/* CGBpalette entries. */
extern const unsigned char HeroCGB[];
/* Start of tile array. */
extern const unsigned char Hero[];

#endif

/* End of HERO.H */
