/*

 SWORD.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 16 x 16
  Tiles                : 0 to 7

  Palette colors       : Included.
  SGB Palette          : None.
  CGB Palette          : 4 Bits per entry.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

#ifndef __Sword_h_INCLUDE
#define __Sword_h_INCLUDE

/* Bank of tiles. */
#define SwordTileBank 0

/* Super Gameboy palette 0 */
#define SwordTileSGBPal0c0 6076
#define SwordTileSGBPal0c1 8935
#define SwordTileSGBPal0c2 6596
#define SwordTileSGBPal0c3 5344

/* Super Gameboy palette 1 */
#define SwordTileSGBPal1c0 6076
#define SwordTileSGBPal1c1 8935
#define SwordTileSGBPal1c2 6596
#define SwordTileSGBPal1c3 5344

/* Super Gameboy palette 2 */
#define SwordTileSGBPal2c0 6076
#define SwordTileSGBPal2c1 8935
#define SwordTileSGBPal2c2 6596
#define SwordTileSGBPal2c3 5344

/* Super Gameboy palette 3 */
#define SwordTileSGBPal3c0 6076
#define SwordTileSGBPal3c1 8935
#define SwordTileSGBPal3c2 6596
#define SwordTileSGBPal3c3 5344

/* Gameboy Color palette 0 */
#define SwordTileCGBPal0c0 32767
#define SwordTileCGBPal0c1 32767
#define SwordTileCGBPal0c2 25368
#define SwordTileCGBPal0c3 0

/* Gameboy Color palette 1 */
#define SwordTileCGBPal1c0 6076
#define SwordTileCGBPal1c1 8935
#define SwordTileCGBPal1c2 6596
#define SwordTileCGBPal1c3 5344

/* Gameboy Color palette 2 */
#define SwordTileCGBPal2c0 6076
#define SwordTileCGBPal2c1 8935
#define SwordTileCGBPal2c2 6596
#define SwordTileCGBPal2c3 5344

/* Gameboy Color palette 3 */
#define SwordTileCGBPal3c0 6076
#define SwordTileCGBPal3c1 8935
#define SwordTileCGBPal3c2 6596
#define SwordTileCGBPal3c3 5344

/* Gameboy Color palette 4 */
#define SwordTileCGBPal4c0 6076
#define SwordTileCGBPal4c1 8935
#define SwordTileCGBPal4c2 6596
#define SwordTileCGBPal4c3 5344

/* Gameboy Color palette 5 */
#define SwordTileCGBPal5c0 6076
#define SwordTileCGBPal5c1 8935
#define SwordTileCGBPal5c2 6596
#define SwordTileCGBPal5c3 5344

/* Gameboy Color palette 6 */
#define SwordTileCGBPal6c0 6076
#define SwordTileCGBPal6c1 8935
#define SwordTileCGBPal6c2 6596
#define SwordTileCGBPal6c3 5344

/* Gameboy Color palette 7 */
#define SwordTileCGBPal7c0 6076
#define SwordTileCGBPal7c1 8935
#define SwordTileCGBPal7c2 6596
#define SwordTileCGBPal7c3 5344
/* CGBpalette entries. */
extern const unsigned char SwordTileCGB[];
/* Start of tile array. */
extern const unsigned char SwordTile[];

#endif

/* End of SWORD.H */
