/*

 êSTONECAVE.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 16 x 16
  Tiles                : 0 to 12

  Palette colors       : Included.
  SGB Palette          : None.
  CGB Palette          : 4 Bits per entry.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

#ifndef ___StoneCave_h_INCLUDE
#define ___StoneCave_h_INCLUDE

/* Bank of tiles. */
#define StoneCaveTileBank 0

/* Super Gameboy palette 0 */
#define StoneCaveTileSGBPal0c0 6076
#define StoneCaveTileSGBPal0c1 8935
#define StoneCaveTileSGBPal0c2 6596
#define StoneCaveTileSGBPal0c3 5344

/* Super Gameboy palette 1 */
#define StoneCaveTileSGBPal1c0 6076
#define StoneCaveTileSGBPal1c1 8935
#define StoneCaveTileSGBPal1c2 6596
#define StoneCaveTileSGBPal1c3 5344

/* Super Gameboy palette 2 */
#define StoneCaveTileSGBPal2c0 6076
#define StoneCaveTileSGBPal2c1 8935
#define StoneCaveTileSGBPal2c2 6596
#define StoneCaveTileSGBPal2c3 5344

/* Super Gameboy palette 3 */
#define StoneCaveTileSGBPal3c0 6076
#define StoneCaveTileSGBPal3c1 8935
#define StoneCaveTileSGBPal3c2 6596
#define StoneCaveTileSGBPal3c3 5344

/* Gameboy Color palette 0 */
#define StoneCaveTileCGBPal0c0 32767
#define StoneCaveTileCGBPal0c1 25169
#define StoneCaveTileCGBPal0c2 20910
#define StoneCaveTileCGBPal0c3 13544

/* Gameboy Color palette 1 */
#define StoneCaveTileCGBPal1c0 14800
#define StoneCaveTileCGBPal1c1 9515
#define StoneCaveTileCGBPal1c2 6344
#define StoneCaveTileCGBPal1c3 1157

/* Gameboy Color palette 2 */
#define StoneCaveTileCGBPal2c0 15852
#define StoneCaveTileCGBPal2c1 13737
#define StoneCaveTileCGBPal2c2 10565
#define StoneCaveTileCGBPal2c3 8420

/* Gameboy Color palette 3 */
#define StoneCaveTileCGBPal3c0 21137
#define StoneCaveTileCGBPal3c1 19022
#define StoneCaveTileCGBPal3c2 15850
#define StoneCaveTileCGBPal3c3 13705

/* Gameboy Color palette 4 */
#define StoneCaveTileCGBPal4c0 17971
#define StoneCaveTileCGBPal4c1 12686
#define StoneCaveTileCGBPal4c2 9515
#define StoneCaveTileCGBPal4c3 3304

/* Gameboy Color palette 5 */
#define StoneCaveTileCGBPal5c0 32767
#define StoneCaveTileCGBPal5c1 8935
#define StoneCaveTileCGBPal5c2 6596
#define StoneCaveTileCGBPal5c3 0

/* Gameboy Color palette 6 */
#define StoneCaveTileCGBPal6c0 6076
#define StoneCaveTileCGBPal6c1 8935
#define StoneCaveTileCGBPal6c2 6596
#define StoneCaveTileCGBPal6c3 5344

/* Gameboy Color palette 7 */
#define StoneCaveTileCGBPal7c0 6076
#define StoneCaveTileCGBPal7c1 8935
#define StoneCaveTileCGBPal7c2 6596
#define StoneCaveTileCGBPal7c3 5344
/* CGBpalette entries. */
extern const unsigned char StoneCaveTileCGB[];
/* Start of tile array. */
extern const unsigned char StoneCaveTile[];

#endif

/* End of êSTONECAVE.H */
